#!/bin/bash
# Checks and configures Nginx to listen on port 80.

grep -q 'listen\s*80' /etc/nginx/nginx.conf || sed -i 's/listen\s*\(.*\);/listen 80;/g' /etc/nginx/nginx.conf
if ! pgrep nginx >/dev/null; then nginx; fi
