#!/usr/bin/env bash
# Check if Nginx is already configured to listen on port 80
if ! grep -q 'listen\s*80' /etc/nginx/sites-available/default; then
    ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
fi
if [ ! -e /run/nginx.pid ]; then
    nginx
fi
