#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

grep -q 'listen\s*80' /etc/nginx/sites-available/default || ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
[ ! -e /run/nginx.pid ] && nginx

