#!/usr/bin/env bash
# Set nginx user and group
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx /var/cache/nginx
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart

