#!/usr/bin/env bash
# Set nginx user and group
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf

# Change ownership of necessary directories
chown -R nginx:nginx /var/log/nginx /var/cache/nginx

# Modify nginx configuration to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart

